# Generated by Django 4.2 on 2023-05-02 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='followed+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower+', to=settings.AUTH_USER_MODEL),
        ),
    ]
