# Generated by Django 4.2 on 2023-05-02 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
